<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="39" passed="22" failed="17" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-17T12:23:43 IST" name="Idrx Test Automation Suite" finished-at="2025-06-17T12:25:58 IST" duration-ms="135208">
    <groups>
    </groups>
    <test started-at="2025-06-17T12:23:43 IST" name="Retail Test" finished-at="2025-06-17T12:24:05 IST" duration-ms="22307">
      <class name="com.idrx.qa.testcases.RetailPageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.idrx.qa.testcases.RetailPageTest@5812f68b]" started-at="2025-06-17T12:23:43 IST" name="setUp" finished-at="2025-06-17T12:24:00 IST" duration-ms="17026" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="vehicleSoldTest()[pri:1, instance:com.idrx.qa.testcases.RetailPageTest@5812f68b]" started-at="2025-06-17T12:24:00 IST" name="vehicleSoldTest" finished-at="2025-06-17T12:24:03 IST" duration-ms="2745" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- vehicleSoldTest -->
        <test-method signature="vehicleSalesTest()[pri:2, instance:com.idrx.qa.testcases.RetailPageTest@5812f68b]" started-at="2025-06-17T12:24:03 IST" name="vehicleSalesTest" finished-at="2025-06-17T12:24:03 IST" duration-ms="355" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- vehicleSalesTest -->
        <test-method signature="vehicleBookedYesterdayTest()[pri:3, instance:com.idrx.qa.testcases.RetailPageTest@5812f68b]" started-at="2025-06-17T12:24:03 IST" name="vehicleBookedYesterdayTest" finished-at="2025-06-17T12:24:03 IST" duration-ms="316" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- vehicleBookedYesterdayTest -->
        <test-method signature="vehicleInvoicedYesterdayTest()[pri:4, instance:com.idrx.qa.testcases.RetailPageTest@5812f68b]" started-at="2025-06-17T12:24:03 IST" name="vehicleInvoicedYesterdayTest" finished-at="2025-06-17T12:24:04 IST" duration-ms="330" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- vehicleInvoicedYesterdayTest -->
        <test-method signature="vehicleInvoicedThisMonthTest()[pri:5, instance:com.idrx.qa.testcases.RetailPageTest@5812f68b]" started-at="2025-06-17T12:24:04 IST" name="vehicleInvoicedThisMonthTest" finished-at="2025-06-17T12:24:04 IST" duration-ms="320" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- vehicleInvoicedThisMonthTest -->
        <test-method signature="vehicleInvoicedButNotDeliveredTest()[pri:6, instance:com.idrx.qa.testcases.RetailPageTest@5812f68b]" started-at="2025-06-17T12:24:04 IST" name="vehicleInvoicedButNotDeliveredTest" finished-at="2025-06-17T12:24:04 IST" duration-ms="340" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- vehicleInvoicedButNotDeliveredTest -->
        <test-method signature="currentMonthTest()[pri:7, instance:com.idrx.qa.testcases.RetailPageTest@5812f68b]" started-at="2025-06-17T12:24:04 IST" name="currentMonthTest" finished-at="2025-06-17T12:24:05 IST" duration-ms="323" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- currentMonthTest -->
        <test-method signature="lastMonthSalesTrendTest()[pri:8, instance:com.idrx.qa.testcases.RetailPageTest@5812f68b]" started-at="2025-06-17T12:24:05 IST" name="lastMonthSalesTrendTest" finished-at="2025-06-17T12:24:05 IST" duration-ms="314" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lastMonthSalesTrendTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.idrx.qa.testcases.RetailPageTest@5812f68b]" started-at="2025-06-17T12:24:05 IST" name="tearDown" finished-at="2025-06-17T12:24:05 IST" duration-ms="197" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.idrx.qa.testcases.RetailPageTest -->
    </test> <!-- Retail Test -->
    <test started-at="2025-06-17T12:24:05 IST" name="Bookings Test" finished-at="2025-06-17T12:24:27 IST" duration-ms="21793">
      <class name="com.idrx.qa.testcases.BookingsPageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.idrx.qa.testcases.BookingsPageTest@4ce1d6d0]" started-at="2025-06-17T12:24:05 IST" name="setUp" finished-at="2025-06-17T12:24:24 IST" duration-ms="18525" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="bookingYesterdayTest()[pri:1, instance:com.idrx.qa.testcases.BookingsPageTest@4ce1d6d0]" started-at="2025-06-17T12:24:24 IST" name="bookingYesterdayTest" finished-at="2025-06-17T12:24:25 IST" duration-ms="1225" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bookingYesterdayTest -->
        <test-method signature="bookingThisMonthTest()[pri:2, instance:com.idrx.qa.testcases.BookingsPageTest@4ce1d6d0]" started-at="2025-06-17T12:24:25 IST" name="bookingThisMonthTest" finished-at="2025-06-17T12:24:25 IST" duration-ms="342" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bookingThisMonthTest -->
        <test-method signature="pendingBookingsTest()[pri:3, instance:com.idrx.qa.testcases.BookingsPageTest@4ce1d6d0]" started-at="2025-06-17T12:24:25 IST" name="pendingBookingsTest" finished-at="2025-06-17T12:24:26 IST" duration-ms="377" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pendingBookingsTest -->
        <test-method signature="previousMonthTest()[pri:4, instance:com.idrx.qa.testcases.BookingsPageTest@4ce1d6d0]" started-at="2025-06-17T12:24:26 IST" name="previousMonthTest" finished-at="2025-06-17T12:24:26 IST" duration-ms="405" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- previousMonthTest -->
        <test-method signature="currentMonthTest()[pri:5, instance:com.idrx.qa.testcases.BookingsPageTest@4ce1d6d0]" started-at="2025-06-17T12:24:26 IST" name="currentMonthTest" finished-at="2025-06-17T12:24:27 IST" duration-ms="355" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- currentMonthTest -->
        <test-method signature="salesmanWisePendingBookingsTest()[pri:6, instance:com.idrx.qa.testcases.BookingsPageTest@4ce1d6d0]" started-at="2025-06-17T12:24:27 IST" name="salesmanWisePendingBookingsTest" finished-at="2025-06-17T12:24:27 IST" duration-ms="377" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- salesmanWisePendingBookingsTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.idrx.qa.testcases.BookingsPageTest@4ce1d6d0]" started-at="2025-06-17T12:24:27 IST" name="tearDown" finished-at="2025-06-17T12:24:27 IST" duration-ms="182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.idrx.qa.testcases.BookingsPageTest -->
    </test> <!-- Bookings Test -->
    <test started-at="2025-06-17T12:24:27 IST" name="Delivery Test" finished-at="2025-06-17T12:24:49 IST" duration-ms="21480">
      <class name="com.idrx.qa.testcases.DeliveryPageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.idrx.qa.testcases.DeliveryPageTest@2dcd168a]" started-at="2025-06-17T12:24:27 IST" name="setUp" finished-at="2025-06-17T12:24:45 IST" duration-ms="18321" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="deliveryYesterdayTest()[pri:1, instance:com.idrx.qa.testcases.DeliveryPageTest@2dcd168a]" started-at="2025-06-17T12:24:45 IST" name="deliveryYesterdayTest" finished-at="2025-06-17T12:24:47 IST" duration-ms="1328" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deliveryYesterdayTest -->
        <test-method signature="deliveryThisMonthTest()[pri:2, instance:com.idrx.qa.testcases.DeliveryPageTest@2dcd168a]" started-at="2025-06-17T12:24:47 IST" name="deliveryThisMonthTest" finished-at="2025-06-17T12:24:47 IST" duration-ms="322" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deliveryThisMonthTest -->
        <test-method signature="deliveryPendingTest()[pri:3, instance:com.idrx.qa.testcases.DeliveryPageTest@2dcd168a]" started-at="2025-06-17T12:24:47 IST" name="deliveryPendingTest" finished-at="2025-06-17T12:24:47 IST" duration-ms="331" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deliveryPendingTest -->
        <test-method signature="deliveryPreviousMonthTest()[pri:4, instance:com.idrx.qa.testcases.DeliveryPageTest@2dcd168a]" started-at="2025-06-17T12:24:47 IST" name="deliveryPreviousMonthTest" finished-at="2025-06-17T12:24:48 IST" duration-ms="311" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deliveryPreviousMonthTest -->
        <test-method signature="deliveryCurrentMonthTest()[pri:5, instance:com.idrx.qa.testcases.DeliveryPageTest@2dcd168a]" started-at="2025-06-17T12:24:48 IST" name="deliveryCurrentMonthTest" finished-at="2025-06-17T12:24:48 IST" duration-ms="337" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deliveryCurrentMonthTest -->
        <test-method signature="deliverySalesmanWisePendingTest()[pri:6, instance:com.idrx.qa.testcases.DeliveryPageTest@2dcd168a]" started-at="2025-06-17T12:24:48 IST" name="deliverySalesmanWisePendingTest" finished-at="2025-06-17T12:24:48 IST" duration-ms="333" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deliverySalesmanWisePendingTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.idrx.qa.testcases.DeliveryPageTest@2dcd168a]" started-at="2025-06-17T12:24:48 IST" name="tearDown" finished-at="2025-06-17T12:24:49 IST" duration-ms="193" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.idrx.qa.testcases.DeliveryPageTest -->
    </test> <!-- Delivery Test -->
    <test started-at="2025-06-17T12:24:49 IST" name="Discount Test" finished-at="2025-06-17T12:25:14 IST" duration-ms="25836">
      <class name="com.idrx.qa.testcases.DiscountPageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.idrx.qa.testcases.DiscountPageTest@16fdec90]" started-at="2025-06-17T12:24:49 IST" name="setUp" finished-at="2025-06-17T12:25:07 IST" duration-ms="18053" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="noOfDiscountUnitsTest()[pri:1, instance:com.idrx.qa.testcases.DiscountPageTest@16fdec90]" started-at="2025-06-17T12:25:07 IST" name="noOfDiscountUnitsTest" finished-at="2025-06-17T12:25:08 IST" duration-ms="1046" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[No. of Discount Units expected [35] but found [30]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: No. of Discount Units expected [35] but found [30]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.DiscountPageTest.noOfDiscountUnitsTest(DiscountPageTest.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- noOfDiscountUnitsTest -->
        <test-method signature="totalDiscountValueTest()[pri:2, instance:com.idrx.qa.testcases.DiscountPageTest@16fdec90]" started-at="2025-06-17T12:25:08 IST" name="totalDiscountValueTest" finished-at="2025-06-17T12:25:08 IST" duration-ms="331" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Total Discount Value expected [₹ 4.79 Cr] but found [₹ 5.89 L]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Total Discount Value expected [₹ 4.79 Cr] but found [₹ 5.89 L]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.DiscountPageTest.totalDiscountValueTest(DiscountPageTest.java:63)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- totalDiscountValueTest -->
        <test-method signature="totalDiscountQtyTest()[pri:3, instance:com.idrx.qa.testcases.DiscountPageTest@16fdec90]" started-at="2025-06-17T12:25:08 IST" name="totalDiscountQtyTest" finished-at="2025-06-17T12:25:09 IST" duration-ms="337" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Total Discount Qty expected [35] but found [30]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Total Discount Qty expected [35] but found [30]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.DiscountPageTest.totalDiscountQtyTest(DiscountPageTest.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- totalDiscountQtyTest -->
        <test-method signature="totalDiscountAmountTest()[pri:4, instance:com.idrx.qa.testcases.DiscountPageTest@16fdec90]" started-at="2025-06-17T12:25:09 IST" name="totalDiscountAmountTest" finished-at="2025-06-17T12:25:09 IST" duration-ms="372" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Total Discount Amount expected [₹ 4.79 Cr] but found [₹ 5.89 L]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Total Discount Amount expected [₹ 4.79 Cr] but found [₹ 5.89 L]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.DiscountPageTest.totalDiscountAmountTest(DiscountPageTest.java:87)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- totalDiscountAmountTest -->
        <test-method signature="currentMonthValueTest()[pri:5, instance:com.idrx.qa.testcases.DiscountPageTest@16fdec90]" started-at="2025-06-17T12:25:09 IST" name="currentMonthValueTest" finished-at="2025-06-17T12:25:10 IST" duration-ms="322" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Current Month Value expected [₹ 4.79 Cr] but found [₹ 5.89 L]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Current Month Value expected [₹ 4.79 Cr] but found [₹ 5.89 L]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.DiscountPageTest.currentMonthValueTest(DiscountPageTest.java:125)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- currentMonthValueTest -->
        <test-method signature="previousMonthValueTest()[pri:6, instance:com.idrx.qa.testcases.DiscountPageTest@16fdec90]" started-at="2025-06-17T12:25:10 IST" name="previousMonthValueTest" finished-at="2025-06-17T12:25:10 IST" duration-ms="351" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Previous Month Value expected [₹ 4.79 Cr] but found [₹ 39.76 L]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Previous Month Value expected [₹ 4.79 Cr] but found [₹ 39.76 L]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.DiscountPageTest.previousMonthValueTest(DiscountPageTest.java:136)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- previousMonthValueTest -->
        <test-method signature="currentMonthUnitsTest()[pri:7, instance:com.idrx.qa.testcases.DiscountPageTest@16fdec90]" started-at="2025-06-17T12:25:10 IST" name="currentMonthUnitsTest" finished-at="2025-06-17T12:25:14 IST" duration-ms="3711" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Current Month Units expected [35] but found [30]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Current Month Units expected [35] but found [30]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.DiscountPageTest.currentMonthUnitsTest(DiscountPageTest.java:102)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- currentMonthUnitsTest -->
        <test-method signature="previousMonthUnitsTest()[pri:8, instance:com.idrx.qa.testcases.DiscountPageTest@16fdec90]" started-at="2025-06-17T12:25:14 IST" name="previousMonthUnitsTest" finished-at="2025-06-17T12:25:14 IST" duration-ms="314" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Previous Month Units expected [35] but found [129]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Previous Month Units expected [35] but found [129]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.DiscountPageTest.previousMonthUnitsTest(DiscountPageTest.java:114)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- previousMonthUnitsTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.idrx.qa.testcases.DiscountPageTest@16fdec90]" started-at="2025-06-17T12:25:14 IST" name="tearDown" finished-at="2025-06-17T12:25:14 IST" duration-ms="164" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.idrx.qa.testcases.DiscountPageTest -->
    </test> <!-- Discount Test -->
    <test started-at="2025-06-17T12:25:15 IST" name="Finance Test" finished-at="2025-06-17T12:25:37 IST" duration-ms="22891">
      <class name="com.idrx.qa.testcases.FinancePageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.idrx.qa.testcases.FinancePageTest@3a0baae5]" started-at="2025-06-17T12:25:15 IST" name="setUp" finished-at="2025-06-17T12:25:33 IST" duration-ms="18787" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="noOfFinanceQtyTest()[pri:1, instance:com.idrx.qa.testcases.FinancePageTest@3a0baae5]" started-at="2025-06-17T12:25:33 IST" name="noOfFinanceQtyTest" finished-at="2025-06-17T12:25:34 IST" duration-ms="1157" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[No. of Finance Qty expected [35] but found [131]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: No. of Finance Qty expected [35] but found [131]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.FinancePageTest.noOfFinanceQtyTest(FinancePageTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- noOfFinanceQtyTest -->
        <test-method signature="financePenetrationTest()[pri:2, instance:com.idrx.qa.testcases.FinancePageTest@3a0baae5]" started-at="2025-06-17T12:25:35 IST" name="financePenetrationTest" finished-at="2025-06-17T12:25:35 IST" duration-ms="376" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Finance Penetration expected [35] but found [83.44%]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Finance Penetration expected [35] but found [83.44%]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.FinancePageTest.financePenetrationTest(FinancePageTest.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- financePenetrationTest -->
        <test-method signature="cashVsFinanceTotalTest()[pri:3, instance:com.idrx.qa.testcases.FinancePageTest@3a0baae5]" started-at="2025-06-17T12:25:35 IST" name="cashVsFinanceTotalTest" finished-at="2025-06-17T12:25:35 IST" duration-ms="338" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Cash vs Finance Total expected [35] but found [157]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Cash vs Finance Total expected [35] but found [157]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.FinancePageTest.cashVsFinanceTotalTest(FinancePageTest.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cashVsFinanceTotalTest -->
        <test-method signature="currentMonthFinanceTrendTest()[pri:4, instance:com.idrx.qa.testcases.FinancePageTest@3a0baae5]" started-at="2025-06-17T12:25:35 IST" name="currentMonthFinanceTrendTest" finished-at="2025-06-17T12:25:36 IST" duration-ms="334" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Current Month Finance Trend expected [35] but found [29]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Current Month Finance Trend expected [35] but found [29]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.FinancePageTest.currentMonthFinanceTrendTest(FinancePageTest.java:91)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- currentMonthFinanceTrendTest -->
        <test-method signature="previousMonthFinanceTrendTest()[pri:5, instance:com.idrx.qa.testcases.FinancePageTest@3a0baae5]" started-at="2025-06-17T12:25:36 IST" name="previousMonthFinanceTrendTest" finished-at="2025-06-17T12:25:36 IST" duration-ms="344" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Previous Month Finance Trend expected [35] but found [141]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Previous Month Finance Trend expected [35] but found [141]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.FinancePageTest.previousMonthFinanceTrendTest(FinancePageTest.java:104)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- previousMonthFinanceTrendTest -->
        <test-method signature="currentMonthFinancePenetrationTrendTest()[pri:6, instance:com.idrx.qa.testcases.FinancePageTest@3a0baae5]" started-at="2025-06-17T12:25:36 IST" name="currentMonthFinancePenetrationTrendTest" finished-at="2025-06-17T12:25:37 IST" duration-ms="319" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Current Month Finance Penetration Trend expected [35] but found [83%]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Current Month Finance Penetration Trend expected [35] but found [83%]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.FinancePageTest.currentMonthFinancePenetrationTrendTest(FinancePageTest.java:116)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- currentMonthFinancePenetrationTrendTest -->
        <test-method signature="previousMonthFinancePenetrationTrendTest()[pri:7, instance:com.idrx.qa.testcases.FinancePageTest@3a0baae5]" started-at="2025-06-17T12:25:37 IST" name="previousMonthFinancePenetrationTrendTest" finished-at="2025-06-17T12:25:37 IST" duration-ms="308" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Previous Month Finance Penetration Trend expected [35] but found [83%]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Previous Month Finance Penetration Trend expected [35] but found [83%]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.FinancePageTest.previousMonthFinancePenetrationTrendTest(FinancePageTest.java:127)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- previousMonthFinancePenetrationTrendTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.idrx.qa.testcases.FinancePageTest@3a0baae5]" started-at="2025-06-17T12:25:37 IST" name="tearDown" finished-at="2025-06-17T12:25:37 IST" duration-ms="201" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.idrx.qa.testcases.FinancePageTest -->
    </test> <!-- Finance Test -->
    <test started-at="2025-06-17T12:25:37 IST" name="Parts Sales Test" finished-at="2025-06-17T12:25:58 IST" duration-ms="20778">
      <class name="com.idrx.qa.testcases.PartsSalesTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.idrx.qa.testcases.PartsSalesTest@4c51cf28]" started-at="2025-06-17T12:25:37 IST" name="setUp" finished-at="2025-06-17T12:25:55 IST" duration-ms="17841" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="noofQtyTest()[pri:1, instance:com.idrx.qa.testcases.PartsSalesTest@4c51cf28]" started-at="2025-06-17T12:25:55 IST" name="noofQtyTest" finished-at="2025-06-17T12:25:56 IST" duration-ms="1191" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[No of Qty expected [31907] but found [31908]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: No of Qty expected [31907] but found [31908]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.PartsSalesTest.noofQtyTest(PartsSalesTest.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- noofQtyTest -->
        <test-method signature="partsSalesTest()[pri:2, instance:com.idrx.qa.testcases.PartsSalesTest@4c51cf28]" started-at="2025-06-17T12:25:57 IST" name="partsSalesTest" finished-at="2025-06-17T12:25:57 IST" duration-ms="444" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Parts Sales expected [₹ 1.5 Cr] but found [₹1.5 Cr]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Parts Sales expected [₹ 1.5 Cr] but found [₹1.5 Cr]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.idrx.qa.util.TestUtil.assertEquals(TestUtil.java:90)
at com.idrx.qa.testcases.PartsSalesTest.partsSalesTest(PartsSalesTest.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- partsSalesTest -->
        <test-method signature="thisMonthTest()[pri:3, instance:com.idrx.qa.testcases.PartsSalesTest@4c51cf28]" started-at="2025-06-17T12:25:57 IST" name="thisMonthTest" finished-at="2025-06-17T12:25:58 IST" duration-ms="467" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thisMonthTest -->
        <test-method signature="previousMonthTest()[pri:4, instance:com.idrx.qa.testcases.PartsSalesTest@4c51cf28]" started-at="2025-06-17T12:25:58 IST" name="previousMonthTest" finished-at="2025-06-17T12:25:58 IST" duration-ms="422" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- previousMonthTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.idrx.qa.testcases.PartsSalesTest@4c51cf28]" started-at="2025-06-17T12:25:58 IST" name="tearDown" finished-at="2025-06-17T12:25:58 IST" duration-ms="198" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.idrx.qa.testcases.PartsSalesTest -->
    </test> <!-- Parts Sales Test -->
  </suite> <!-- Idrx Test Automation Suite -->
</testng-results>
